* Business

** Business Value

There are two concepts related with delivering business value - *costs
center* and *profit center*. Profit centers are most important, it is
a core business value, you have got permission to do everything what
is necessary to deliver and maintain profits. And that is the core
domain, and most interesting problems to resolve.

On the other hand, problems related with *costs center* are trivial,
boring, management will always reduce operational costs and expenses,
it will endeavor to outsourcing it, outside the company.

Profit centers are much more important than cost centers, so you
should always strive to being on the *profit center* side. If you
cannot do that, it is time to switch project or even job. Or you
should deal with it that you will not have significant influence on
the project and direction of development.

You have to learn to speak in language of benefits and costs, like the
management does, you are not paid by writing code, but for solving
business problems, either by reducing costs or increasing
profits. Asks yourself a question "How did you help your company to
increase profit or reduce costs lately?". You should prepare answers
for that question for your next job interview.
