* Learning How to Learn

** Modes of Thinking

*** Comment

- Analogy to *pinball* with close bumpers (focused mode) and looser bumpers
  (diffuse mode), the later eases learning and recognizing new thought patterns.
- You can be in *one mode* at a time.
- Switching between two modes speeds-up the learning process.
  - It needs systematic exercises, strengthening and building your neural
    structure.

*** Focused

- Narrow
- Repeatable
- Bright
- Well-known
- Concrete

*** Diffuse

- Wide
- Doing something for the first time
- Dimmed
- Unknown
- Reflective

** Problems

*** Procrastination

- Appears when you starts working with something new, unfamiliar. It activates
  areas of the brain that are responsible for pain (*insular cortex*).
- Researches shows that right after you start working with an activity you don't
  like, unhappy feeling disappears.
- You are switching from unpleasant thing to more pleasant one, in order to
  satisfy your brain, temporarily.
- Doing *pomodoro* helps with interruptions and helps to exchange modes -
  focused for 25 minutes and diffused for 5 minutes (as a reward).

*** Practice Makes Permanent

- Learn hard, for a while - then rest and wander in mind, it helps build neural
  patterns.

** Memory

*** Long term memory

- A structured warehouse, different parts of that memory are distributed in
  various places in brain. Studies were shown that you need to use certain part
  of the long term memory in order to increase probability that you will find
  it. The more that part it is used, the more easily you will return to that
  thought pattern.
- It takes time to move elements from working memory to long term memory.
  - There is a technique called *spaced repetition*.
  - Extending your practice over several days it will *stick* much easier and
    will be much more durable.

*** Working memory

- Is centered in *prefrontal Cortex*, but has connections to other parts of
  brain, related with long term memory.
- Working memory can hold 7 +/- 2 items.
  - It is not a very good blackboard, you need to repeat facts from that type of
    memory in order to remember.

** Sleep

- During the work a *toxic poisons* are produced in our brains. It will be
  removed during the sleep and recovery process.
- Sleeping keeps your brainwaves healthy and clean, brain cells are shrinking
  during the sleep, so a fluid can wash and flow between them and remove toxins
  out. 
- It is also related with amount of sleep and how long and effective you will
  rest.
- During sleep neural patterns are strengthen and rewritten over again and
  again. But you need to do a focused mode work first. Again - *focused*
  vs. *diffuse* thinking modes.

** Tricks, Notes and Reflections

- Learning by doing (practice over theory).
- Learning by osmosis (surrounded by *experts* in the field).
- You are born with neurons, but in *hipocampus* new neurons and brain cells are
  created even if you are an adult. What is even more important - physical
  exercises or new, sometimes hostile environment also increases the rate of
  survived and newborn neurons.
- Changing way of learning - explaining, teaching, making notes, making
  mind-maps, hand-writing, drawing, manual exercises, taking a new perspective
  on the topic.
- Success comes with passion and persistence, not only by smartness.
- Balancing between consciousness or sleeping (Salvador Dali trick, falling to
  sleep with keys in the hands when you will fly away keys will hit the ground
  and noise will wake you up, and for a while you will be able to have ideas
  from subconscious sleep about your problems).
