site :opscode

cookbook 'java'
cookbook 'runit'

cookbook 'mongodb'
cookbook 'couchdb'
cookbook 'redisio'
cookbook 'postgresql'
cookbook 'riak', path: './cookbooks/riak'
cookbook 'hbase', path: './cookbooks/hbase'
cookbook 'neo4j', path: './cookbooks/neo4j'