source 'https://rubygems.org'

gem 'chef',                                                           '11.10.4'

gem 'berkshelf',                                                      '~> 2.0.0'
gem 'foodcritic'

gem 'vagrant',              github: 'mitchellh/vagrant',              tag: 'v1.4.3'

gem 'vagrant-cachier',      github: 'fgrehm/vagrant-cachier',         tag: 'v0.2.0'
gem 'vagrant-vbguest',      github: 'dotless-de/vagrant-vbguest'
gem 'vagrant-omnibus',      github: 'schisamo/vagrant-omnibus'
gem 'vagrant-hostsupdater', github: 'cogitatio/vagrant-hostsupdater'

gem 'test-kitchen'
gem 'kitchen-vagrant'