* 'Learn You Some Erlang for Great Good!'
** 'Let it Crash'
** Tools

Various tools (especially databases and with high requirements regarding distribution) are created in Erlang.

*** Services

- RabbitMQ
  - It has very nice simulator (Node.js based).
- Riak
- CouchDB

*** Developer Tools

- Rebar
  - Also has bootstrapping new application tool inside.
- Emacs
- EDoc Annotations

*** Libraries

- WebMachine
  - It has impressive tool which creates diagram for each request.

** OTP (Open Telecom Platform)

*** Behaviors

It's a specification that dictates which functions your module should export. Concrete module 
that declares that it conforms to a behavior and implement these functions. Run-time component
that can execute behavior-compliant module within the OTP context.

Available behaviors:

**** Supervisor

Process which monitors state of other processes under his control, detects and restarts 
the dead ones. Traps are helpful with detecting erroneous situations. 

**** Links

A link is a specific kind of relationship that can be created between two processes. 
When that relationships 

**** Monitors
**** Named processes
