* Introduction

Software is created in your head.
My comment: so try to not put rubbish into it.

** Wetware

wetware - (etymology) *wet* + *software*; humorous analogy to the
software and hardware, but applied to the biological areas. It is
a reference to the water found in living creatures.

** Context

Context is the most important thing when learning, talking, applying
newly learned stuff. In other words context is a 'king' and should
taken into consideration always.

The key information about context is related with the paths in the
brains activated by certain actions - typing notes on the computer
and in the notebook with pen and paper have the same output. 
However the way and creative process is very different between 
these two approaches.

* Dreyfus Model of Skills Acquisition

Dreyfus brothers created very nice model (5 levels) 
which applies to the single skill, because you can be
a novice in one skill and expert in the others.

** Beginners vs. Experts

Novices need context-free, exact and precise rules how and what to do it.
From the other hand experts should have freedom, if we're applying rules
and guidelines they are feeling constrained and they can't be effective
as they experts really are (*unconscious activities*).

** Levels

*** Novice

- Needs direct and explicit recipes.
- You can't define something explicitly with infinite recursion.
- Directions have to well defined, values have to be exact.
- Analogy: *Call Center workers*.

*** Advanced Beginner
