* Programming Amazon EC2

** History

- Amazon released first feature in 2004 - Simple Queue Service.
- S3 and SQS.
  - Released outside was the side-effect of resolving Amazon Shop scaling problems.

** 'You Built It, You Run It' (Werner Vogels, Amazon CTO)

** Services

*** SQS (Simple Queue Service)

Distributed queue system that enables web service applications to quickly and
reliably queue messages that one component in the application generates to be
consumed by another component.

It is a temporary repository for messages that are awaiting processing.

Use Cases:
- Offloading image processing.
- PDF processing.
- Risk delegation and communication with workers for background jobs.

*** S3 (Simple Storage Service)
*** EC2 (Elastic Compute Cloud)
*** RDS (Relational Database Server)

Highly available and scalable MySQL hosting.

- Scaling Out:
  - Using read-only slaves.
    - Read replica in Amazon RDS.
  - Sharding.
  - Partitioning.
- Scaling Up:
  - Bigger and better instance.

*** CloudFront

CDN (Content Delivery Network) built upon S3.

*** CloudWatch

Monitoring service for rest of services:
- Dimmension
  - Specifies the asset you want to measure.
- Metric
  - It is what you want to measure.
- Namespace
  - This is a source of the measurement.
- Statistics
- Unit

*** ELB (Elastic Load Balancing)

Various load balancing techniques supported by this service.
- Sticky Sessions.
- Round Robin.
- It distributes load evenly across availability zones and across instances within those zones.

It's easier to setup HTTPS -> HTTP drop. Traffic between instances and ELB remain unecrypted.

*** SimpleDB

I/O optimized key-value storage.

A highly available, scalable and flexible nonrelational data store that offloads
the work of database administration. Indexes are implicit. It has consistent read, conditional
put and delete.

Domains are used to store related items.

Items are collection of attributes, item can have 256 attributes, domain a billion items.
At summary up to 10 GB.

Use Cases:
- Loosely coupled systems.
- Fast clients.
- Large, linear datasets.
- Hyperpersonal.
- Scale.

*** DynamoDB

Fully managed NoSQL database.

*** Auto Scaling

Service which monitors traffic on your servers / services and adjust used resources properly.
Launch Configuration determines what kind of instance is being launched - it sets AMI
and the type of instance. It can be configured with alarms triggered from CloudWatch.

*** SNS (Simple Notifications Service)

Notifications service, which requires subscribers and their confirmation. Created in *push model*.
Topics are conduits for sending (publishing) and receiving messages, or events.

Supported endpoints:
- *HTTP* / *HTTPS*
- Email
- *SQS*
- *SMS* (*USA* only)

*** Elastic Beanstalk

Composition of couple services: CloudWatch, Auto Scaling and Elastic Load Balancing.
Also has more features like: Notifications via Amazon SNS.

** SDK

- Everything what you can do from AWS Console is available from command line as well.
- You only need to generate X.509 certificates and SSH key pairs.

** Inevitable Downtime

- Minimize downtime by planning for quick recovery.
- Optimize the application by restricting infrastructure scaling.

*** Improvements

- Benchmarking.
- Tuning.
- The Merits of Virtual Hardware.

** Tools

- Decaf EC2 - Monitor.
  - Free mobile application for monitoring Amazon infrastructure.
- Nagios / Cacti.
  - Over SNMP.
- Monit.
  - Email.
  - Different protocols.
