* Remote
** Philosophy
- Do it meaningfully, with common sense.
- Do not apply it to one person only, because you will alienate him.
- Try to be rational.
- Office is a luxury - if you can afford it, treat it as a luxury and accept
  that it is a cost fallacy.
- Working remotely is more effective if people have something challenging to do.
  - Also working remotely is better because there are no M&Ms (Managers and
    Meetings).
  - A lot of interruptions are also happening at home, but if you are an adult
    and treat work responsibly there is nothing to afraid.
** Excuses
- Most of them sums up to "I will lose control" and other trust issues.
- Also popular one is "big companies (or our companies) did not work that way",
  which is not the case.
  - eBay, IBM, HP, Accenture ...
- If you are afraid that you will lose control, you've got more issues than lack
  of remote work.
** Tips and Tricks how to effectively work remotely
- Virtual Water Cooler - chat with stupid things, rants, discussions which helps
  being part of the team.
- Culture is not a party, drinking, "brogramming", but common values, approach
  to solving problems, collective ownership.
- Build up the feeling of ownership and participation in a tribe - it is harder
  to cheat your tribe than your manager.
** Beware the dragons
- Cabinet fever - beware of alienating people.
- Lack of healthy dose of movement - it is even harder to have 10'000 steps when
  you working remotely, than working from office - even in the same city.
