* Remote
** Philosophy
- Do it meaningfully, with common sense.
- Do not apply it to one person only, because you will alienate him.
- Try to be rational.
- Office is a luxury - if you can afford it, treat it as a luxury and accept
  that it is a cost fallacy.
- Working remotely is more effective if people have something challenging to do.
  - Also working remotely is better because there are no M&Ms (Managers and
    Meetings).
  - A lot of interruptions are also happening at home, but if you are an adult
    and treat work responsibly there is nothing to afraid.
** Excuses
- Most of them sums up to "I will lose control" and other trust issues.
- Also popular one is "big companies (or our companies) did not work that way",
  which is not the case.
  - eBay, IBM, HP, Accenture ...
- If you are afraid that you will lose control, you've got more issues than lack
  of remote work.
** Tips and Tricks how to effectively work remotely
- Virtual Water Cooler - chat with stupid things, rants, discussions which helps
  being part of the team.
- Culture is not a party, drinking, "brogramming", but common values, approach
  to solving problems, collective ownership.
- Build up the feeling of ownership and participation in a tribe - it is harder
  to cheat your tribe than your manager.
** Beware the dragons
- Cabinet fever - beware of alienating people.
- Lack of healthy dose of movement - it is even harder to have 10'000 steps when
  you working remotely, than working from office - even in the same city.
** Take care about relationships
- In remote work the most important thing is a relation with other people, you
  have to care about that. The further you work from HQ, the bond and attitude
  have to be respectively better.
- Seek for humans, positive attitude, "can do" thinking.
- Value people better than way and place where they work - it is easier to try a
  remote work, than lose a person completely.
** Work vs Play
- Clear distinction between work and play (ideally separate devices, maybe
  different slippers - try to reserve informal clothes for after hours).
- Be flexible when it comes to workplace - coworking spaces, coffee shops, your
  apartment - change places, be flexible. It is not all or nothing - you can
  travel from time to time to the office if you have one.
- Plan monthly, quarterly check-ins and 1:1 calls, be prepared and honest.
- Have a daily routine - it is important!
- Be visible - by your work, by your communication, by quality of your work and
  words (be a good writer and practice).
- Remote is flexible, but also it can be painful - be persistent and try to
  split your daily work from life.
