* Zero to One
** 0 to 1 vs. 1 to N
- Being innovative is getting from zero to one, it is a vertical growth,
  creating something completely new, sometimes related with creating the niche
  or new market, more profitable and better perspectives in the long term than
  mimicking other businesses.
- Recreating business is like moving from 1 to N, mostly focused on scaling and
  globalization. It is more risky, often puts you into competitive work, you
  need to have experience in that market and domain, commodity company from
  local to global business. Less profitable and more risky in the long term
  (What happen if the market will be saturated?).
** "What important truth do very few people agree with you on?"
- It is a very nice interview question, not important what do you answer, but
  how. No obvious and best answer, you should focus on something valuable for
  you, and argument both sides of the problem. Obvious statements and positions
  are treated like an easy path.
** Monopoly vs. Competitive Market
- That is not true that competitive market is the best place for you. Only if
  you are prepared and have funds. It is expensive (time and money wise) to
  fight with others. Monopoly from the other hands is purely subjective and
  depends on the point of view (monopoly of income type, monopoly of the market,
  monopoly of the domain). Difference between them is more fluid, it is not
  binary for sure.
- Monopoly has nice conditions for the growing business - being there is
  convenient, it is like a niche, stable place, stable income. Other markets
  which are competitive, are more focused on moving and evolving faster than
  other. In the other words - each happy company is happy in her own way, all
  unhappy companies are unhappy in the same way - they didn't escape competition
  and lost.
- Competitive market does not provide anything good, it often leads to
  pathological cases - like obsession, focusing too much on the fight, it only
  lefts better prepared company, this one which evolved faster or company with
  more money, not particularly the better product.
  - Take an example from Google vs. Microsoft - they could coexist on market
    without interference, but obsession leads to competition - Google Search vs.
    Bing, Windows vs. Chrome OS, Android vs. Windows Phone. And at the end
    they've lost a lot of money and leadership in favor of Apple.
  - Small monopoly area brings profit, longer prosperity, stable income and it
    matters in the long term.
** War is expensive
- You will spent a lot of money on fighting with your enemies. Money, time and
  man-power. You will be more exposed to problems like overlooking opportunities
  and troubles, you may miss many things - including total failure of your
  company.
  - Take an example of Oracle vs. Informix (latter bankrupted, but both CEOs
    were involved in "word fight" over ads).
  - You need to do your stuff, be persistent and avoid war at any cost. Strive
    for minimal monopoly, mutual agreement and symbiosis, coexistence. Hide in
    the trenches, build your castle - building a business is similar to a
    marathon, not fast lane run.
** Economies of Scale
- Monopoly should be based on sustainability and growth. Having only growth ends
  up like in Groupon or Zynga case, when the focusing on growth only causes
  market to collapse.
- When establishing monopoly you have to build an order of magnitude better
  solution (like 10x better) than current actively used. Without that difference
  will be too small and you will be indistinguishable from competitors.
- Network effect is important, but in order to bring momentum you have to start
  small, then establish a base and expand your territory.
- Taking into account the growth it is inscribed into start-up DNA, those
  organizations are based on that assumption.
- Brand is your strong point, you have monopoly on using your brand.
- False promise of having 1% of 100M USD market is not obvious at the first
  sight, it is pure calculation which makes sense but it is not sustainable -
  those 1% are spread, without common ground and good roots, a foundation to
  build on rest of the company. Look at Amazon - it started with books, largest
  bookstore in the world - they've mastered this section well, then moved to
  similar grounds like Software, Music etc.
- As above - focus on small, consistent group which can be served better than
  usual service level is provided in that category, 10x worse competitor
  matters.
- Keep in mind that potential and future valuation is driven by cash flow. The
  more money you can flow through your system the better for you. And our
  potential investors.
- The last will be first, being first on the market is a tactic, a small
  benefit - not a goal or significant advantage.
- Do not disrupt, it is a meaningless buzzword in definition it means
  competition, which you should avoid at all costs, especially when you are
  going from 0 to 1.
** You are not a lottery ticket!
- Companies with solid plan, predictable and easy to verify cash flow that need
  money to grow will be perceived as underrated, because of tyranny of luck and
  randomness in our world. It is related with thinking which of course changed
  across millennia - different generations, different influences and way of
  seeing world. Indefinite optimism is in charge now, you need to be prepared.
** Power of law
- We're not living in normal world (I mean the Gaussian one), power of law rules
  everything. It is reflected in many things e.g. in diversity of VC funding, it
  opens a lot of doors, because beside the great ideas also the not confirmed or
  just worse can benefit. It has to be diverse in order to bring a return of
  investment, you don't know for sure which one will be the next Facebook or
  Uber.
** Secrets
- There is a pseudo-philosophical statement that all hard problems are already
  solved by the people, so only the impossible or trivial ones are available to
  your disposal. Ted Kaczynski formulated that manifesto, but he was a loony. It
  turned out that there is a grain of truth here - often when you are trying at
  least tackle impossible problem people will treat you as a loony.
- But way of thinking about that things can be a good way to focus on most
  important things - instead of fighting with other people, because your point
  of view is different, controversial or just wrong for them. Keep that you are
  working on impossible problem as a secret, share it only with closest and also
  really dedicated people.
- Instead of spending your time and energy on fighting ostracism, and laugh of
  other people focus on most important things for you.
** Foundations
- Messed foundations cannot be fixed by anything. Without solid foundation,
  common rules and single point of view you ship will swing violently.
- Messed relations at the top (founders) also. Without that toxic conflicts can
  kill your company faster then you think.
- Alignment in payment, cash does not create belonging, shares do. You cannot
  create full commitment and the same alignment between founders and workers
  without shares.
- That's why you can't obtain and work reliably with consultants (they're not so
  engaged as you may think, it is kind of theater and play for them, to be the
  best, part-time work and agencies also do not work, remote work is dangerous
  especially if you don't know people).
** Mafia
- Hire people similar to you, interesting in solving the same problems - do not
  focus on money, working with best people and other typical HR moves (like
  playrooms). Build your company on top of solid people, learn from that and be
  wise - proper people will be a motor in your company.
- Hire similar nerds to you. Are you a sci-fi lover? Hire others as well. It is
  like building a mafia, being a part of the cult. The opposite is the
  consulting firm where people are mostly nihilistic.
** Audience and Clients
- Sales are hidden, marketing works. Without that, even the best idea is
  nothing. It is a complex process, requiring a lot of experience, dealing with
  lawyers, politicians, theater and playing.
- The higher stake is, the higher positions people want to see (aka why CEO is a
  kind of salesman also). But in smaller businesses you have to avoid dead zone,
  when amount of money spent on the marketing and sales is still feasible, but
  benefit is negligible.
- You don't have to spent huge piles of money on marketing, if product has a
  viral potential, you can do it in this way.
- Everybody sales, even you developer - if you speak with clients, you're
  selling product - by your attitude, proper language and service.
** Technology
- Man and computer symbiosis, not only the technology matters - sometimes hybrid
  approach is the key (mixing people and computer automated processes).
- Data science, machine learning is one thing. Automating certain tasks and
  using people ability to spot, recognize patterns and be expert in more complex
  domains is the second thing. After a while and after observing such power
  users you will be able to provide at least a semi-automatic solution for that
  problem.
** Seeing green
- Clean energy, energy 2.0 and caring about environment is an important thing,
  especially that it is a future, it affects all of us and we really need a lot
  of 0 to 1 ideas there.
- Being an innovator here is an important mission, and it is challenging to
  actually think small and innovate on small scale, because topic is so wide and
  deep that you drown in it.
