* Zero to One
** 0 to 1 vs. 1 to N
- Being innovative is getting from zero to one, it is a vertical growth,
  creating something completely new, sometimes related with creating the niche
  or new market, more profitable and better perspectives in the long term than
  mimicking other businesses.
- Recreating business is like moving from 1 to N, mostly focused on scaling and
  globalization. It is more risky, often puts you into competitive work, you
  need to have experience in that market and domain, commodity company from
  local to global business. Less profitable and more risky in the long term
  (What happen if the market will be saturated?).
** "What important truth do very few people agree with you on?"
- It is a very nice interview question, not important what do you answer, but
  how. No obvious and best answer, you should focus on something valuable for
  you, and argument both sides of the problem. Obvious statements and positions
  are treated like an easy path.
** Monopoly vs. Competitive Market
- That is not true that competitive market is the best place for you. Only if
  you are prepared and have funds. It is expensive (time and money wise) to
  fight with others. Monopoly from the other hands is purely subjective and
  depends on the point of view (monopoly of income type, monopoly of the market,
  monopoly of the domain). Difference between them is more fluid, it is not
  binary for sure.
- Monopoly has nice conditions for the growing business - being there is
  convenient, it is like a niche, stable place, stable income. Other markets
  which are competitive, are more focused on moving and evolving faster than
  other. In the other words - each happy company is happy in her own way, all
  unhappy companies are unhappy in the same way - they didn't escape competition
  and lost.
- Competitive market does not provide anything good, it often leads to
  pathological cases - like obsession, focusing too much on the fight, it only
  lefts better prepared company, this one which evolved faster or company with
  more money, not particularly the better product.
  - Take an example from Google vs. Microsoft - they could coexist on market
    without interference, but obsession leads to competition - Google Search vs.
    Bing, Windows vs. Chrome OS, Android vs. Windows Phone. And at the end
    they've lost a lot of money and leadership in favor of Apple.
  - Small monopoly area brings profit, longer prosperity, stable income and it
    matters in the long term.
** War is expensive
- You will spent a lot of money on fighting with your enemies. Money, time and
  man-power. You will be more exposed to problems like overlooking opportunities
  and troubles, you may miss many things - including total failure of your
  company.
  - Take an example of Oracle vs. Informix (latter bankrupted, but both CEOs
    were involved in "word fight" over ads).
  - You need to do your stuff, be persistent and avoid war at any cost. Strive
    for minimal monopoly, mutual agreement and symbiosis, coexistence. Hide in
    the trenches, build your castle - building a business is similar to a
    marathon, not fast lane run.
